export const GET_CITIES_LIST = "GET_CITIES_LIST"
export const GET_CITIES_LIST_SUCCESS = "GET_CITIES_LIST_SUCCESS"
export const GET_CITIES_LIST_FAILED = "GET_CITIES_LIST_FAILED"

export const GET_BOOKS_LIST = "GET_BOOKS_LIST"
export const GET_BOOKS_LIST_SUCCESS = "GET_BOOKS_LIST_SUCCESS"
export const GET_BOOKS_LIST_FAILED = "GET_BOOKS_LIST_FAILED"